apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  namespace: default
  labels:
    app: fraud-detection
spec:
  selector:
    app: fraud-detection
  ports:
    - name: http
      port: 8000
      targetPort: 8000
