apiVersion: v1
kind: Service

metadata:
  name: fraud-detection-service

spec:

  type: NodePort

  selector:
    app: fraud-detection

  ports:

  - port: 80
    targetPort: 8000
    nodePort: 30007
